
package com.wst.ifmo.com;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StationWebService", targetNamespace = "http://com.ifmo.wst.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StationWebService {


    /**
     * 
     * @param city
     * @param line
     * @param name
     * @param id
     * @param isend
     * @param type
     * @return
     *     returns int
     * @throws StationException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.UpdateResponse")
    public int update(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "line", targetNamespace = "")
        String line,
        @WebParam(name = "isend", targetNamespace = "")
        Boolean isend,
        @WebParam(name = "type", targetNamespace = "")
        String type)
        throws StationException
    ;

    /**
     * 
     * @param city
     * @param line
     * @param name
     * @param isend
     * @param type
     * @return
     *     returns java.util.List<com.wst.ifmo.com.Station>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.ReadResponse")
    public List<Station> read(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "line", targetNamespace = "")
        String line,
        @WebParam(name = "isend", targetNamespace = "")
        Boolean isend,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param id
     * @return
     *     returns int
     * @throws StationException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.DeleteResponse")
    public int delete(
        @WebParam(name = "id", targetNamespace = "")
        int id)
        throws StationException
    ;

    /**
     * 
     * @param city
     * @param line
     * @param name
     * @param isend
     * @param type
     * @return
     *     returns long
     * @throws StationException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.CreateResponse")
    public long create(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "line", targetNamespace = "")
        String line,
        @WebParam(name = "isend", targetNamespace = "")
        Boolean isend,
        @WebParam(name = "type", targetNamespace = "")
        String type)
        throws StationException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.wst.ifmo.com.Station>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://com.ifmo.wst.com", className = "com.wst.ifmo.com.FindAllResponse")
    public List<Station> findAll();

}
